# Developer network
genesis_time = "2021-12-20T15:00:00.00Z"

# 4 genesis validators.
[validator.validator-1]
# Validator's token balance at genesis.
tokens = 1844674407370 # corresponds to 6_714_000 voting power
# Amount of the validator's genesis token balance which is not staked.
non_staked_balance = 1000000000000
# VP for the validator account
validator_vp = "vp_user"
# VP for the staking reward account
staking_reward_vp = "vp_user"
# Public IP:port address
net_address = "52.210.23.30:26656"
# A seed node is not part of the gossipsub and hence cannot run matchmakers
intent_gossip_seed = true

[validator.validator-2]
# Validator's token balance at genesis.
tokens = 1844674407370
# Amount of the validator's genesis token balance which is not staked.
non_staked_balance = 1000000000000
# VP for the validator account
validator_vp = "vp_user"
# VP for the staking reward account
staking_reward_vp = "vp_user"
# Public IP:port address
net_address = "63.32.203.239:26656"
# This has to be an alias of one of the established accounts
matchmaker_account = "matchmaker-2"
# A matchmaker WASM program
matchmaker_code = "wasm/mm_token_exch.wasm"
# A transaction WASM code used by the matchmaker
matchmaker_tx = "wasm/tx_from_intent.wasm"

[validator.validator-3]
# Validator's token balance at genesis.
tokens = 1844674407370
# Amount of the validator's genesis token balance which is not staked.
non_staked_balance = 1000000000000
# VP for the validator account
validator_vp = "vp_user"
# VP for the staking reward account
staking_reward_vp = "vp_user"
# Public IP:port address
net_address = "54.195.72.213:26656"
# This has to be an alias of one of the established accounts
matchmaker_account = "matchmaker-3"
# A matchmaker WASM program
matchmaker_code = "wasm/mm_token_exch.wasm"
# A transaction WASM code used by the matchmaker
matchmaker_tx = "wasm/tx_from_intent.wasm"

[validator.validator-4]
# Validator's token balance at genesis.
tokens = 1844674407370
# Amount of the validator's genesis token balance which is not staked.
non_staked_balance = 1000000000000
# VP for the validator account
validator_vp = "vp_user"
# VP for the staking reward account
staking_reward_vp = "vp_user"
# Public IP:port address
net_address = "79.125.112.218:26656"
# This has to be an alias of one of the established accounts
matchmaker_account = "matchmaker-4"
# A matchmaker WASM program
matchmaker_code = "wasm/mm_token_exch.wasm"
# A transaction WASM code used by the matchmaker
matchmaker_tx = "wasm/tx_from_intent.wasm"

# Some tokens present at genesis.

[token.XAN]
address = "atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5"
vp = "vp_token"
[token.XAN.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854
atest1v4ehgw36xaryysfsx5unvve4g5my2vjz89p52sjxxgenzd348yuyyv3hg3pnjs35g5unvde4ca36y5 = 9223372036854

[token.BTC]
address = "atest1v4ehgw36xdzryve5gsc52veeg5cnsv2yx5eygvp38qcrvd29xy6rys6p8yc5xvp4xfpy2v694wgwcp"
vp = "vp_token"
[token.BTC.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.ETH]
address = "atest1v4ehgw36xqmr2d3nx3ryvd2xxgmrq33j8qcns33sxezrgv6zxdzrydjrxveygd2yxumrsdpsf9jc2p"
vp = "vp_token"
[token.ETH.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.DOT]
address = "atest1v4ehgw36gg6nvs2zgfpyxsfjgc65yv6pxy6nwwfsxgungdzrggeyzv35gveyxsjyxymyz335hur2jn"
vp = "vp_token"
[token.DOT.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.Schnitzel]
address = "atest1v4ehgw36xue5xvf5xvuyzvpjx5un2v3k8qeyvd3cxdqns32p89rrxd6xx9zngvpegccnzs699rdnnt"
vp = "vp_token"
[token.Schnitzel.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.Apfel]
address = "atest1v4ehgw36gfryydj9g3p5zv3kg9znyd358ycnzsfcggc5gvecgc6ygs2rxv6ry3zpg4zrwdfeumqcz9"
vp = "vp_token"
[token.Apfel.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.Kartoffel]
address = "atest1v4ehgw36gep5ysecxq6nyv3jg3zygv3e89qn2vp48pryxsf4xpznvve5gvmy23fs89pryvf5a6ht90"
public_key = ""
vp = "vp_token"
[token.Kartoffel.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

# Some established accounts present at genesis.
[established.matchmaker-2]
vp = "vp_user"

[established.matchmaker-3]
vp = "vp_user"

[established.matchmaker-4]
vp = "vp_user"

[established.faucet]
address = "atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3"
vp = "vp_testnet_faucet"

[established.masp]
address = "atest1v4ehgw36xaryysfsx5unvve4g5my2vjz89p52sjxxgenzd348yuyyv3hg3pnjs35g5unvde4ca36y5"
vp = "vp_masp"

# Wasm VP definitions

# Default user VP
[wasm.vp_user]
# filename (relative to wasm path used by the node)
filename = "vp_user.wasm"

# Token VP
[wasm.vp_token]
filename = "vp_token.wasm"

# Faucet VP
[wasm.vp_testnet_faucet]
filename = "vp_testnet_faucet.wasm"

# MASP VP
[wasm.vp_masp]
filename = "vp_masp.wasm"

# General protocol parameters.
[parameters]
# Minimum number of blocks in an epoch.
min_num_of_blocks = 100 # block every 10s
# Minimum duration of an epoch (in seconds).
min_duration = 1200 # 20 min
# Maximum expected time per block (in seconds).
max_expected_time_per_block = 30

# Proof of stake parameters.
[pos_params]
# Maximum number of active validators.
max_validator_slots = 128
# Pipeline length (in epochs). Any change in the validator set made in
# epoch 'n' will become active in epoch 'n + pipeline_len'.
pipeline_len = 2
# Unbonding length (in epochs). Validators may have their stake slashed
# for a fault in epoch 'n' up through epoch 'n + unbonding_len'.
unbonding_len = 4
# Votes per token (in basis points, i.e., per 10,000 tokens)
votes_per_token = 10
# Reward for proposing a block.
block_proposer_reward = 100
# Reward for voting on a block.
block_vote_reward = 1
# Portion of a validator's stake that should be slashed on a duplicate
# vote (in basis points, i.e., 500 = 5%).
duplicate_vote_slash_rate = 500
# Portion of a validator's stake that should be slashed on a light
# client attack (in basis points, i.e., 500 = 5%).
light_client_attack_slash_rate = 500

# Governance parameters.
[gov_params]
# minimum amount of xan token to lock
min_proposal_fund = 500
# proposal code size in kibibytes (KiB)
max_proposal_code_size = 300000 
# proposal period length in epoch
min_proposal_period = 3
# maximum number of characters in the proposal content
max_proposal_content_size = 10000
# minimum epochs between end and grace epoch
min_proposal_grace_epochs = 6

# Treasury parameters
[treasury_params]
max_proposal_fund_transfer = 5000
